create table if not exists USERS
(
    ID bigint generated by default as identity primary key,
    NAME varchar(255) not null,
    EMAIL varchar(512) unique not null
);

create table if not exists REQUESTS
(
    ID bigint generated by default as identity primary key,
    DESCRIPTION varchar(1024),
    REQUESTOR bigint unique not null,
    CREATED timestamp,
    foreign key (REQUESTOR) references USERS (ID) on delete  cascade
);

create table if not exists ITEMS
(
    ID bigint generated by default as identity primary key,
    NAME varchar(255) not null,
    DESCRIPTION varchar(1024),
    AVAILABLE boolean,
    OWNER_ID bigint unique not null,
    REQUEST_ID bigint,
    foreign key (OWNER_ID) references USERS (ID) on delete cascade,
    foreign key (REQUEST_ID) references REQUESTS (ID)
);